services:
  web:
    depends_on:
      - "data"
    build: ./server/
    ports:
      - "80:80"

  data:
    image: mysql:latest
    container_name: "mysql-container"
    ports:
      - "3306:3306"
    volumes:
      - /home/ec2-user/qanda_bk.sql:/docker-entrypoint-initdb.d/qanda_bk.sql
    environment:
      MYSQL_ROOT_PASSWORD: "student"
      MYSQL_DATABASE: "qanda"
      MYSQL_USER: "student"
      MYSQL_PASSWORD: "student"
      MYSQL_HOST: "data"
      ALLOW_PUBLIC_KEY_RETRIEVAL: "true"



